# Example: random
import random

print(random.randint(1, 5))  # inclusive
print(random.choice(["McDonald's", "Taco Bell", "Wendy's"]))
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
random.shuffle(my_list)
print(my_list)


# Exercise: Random Number Guesser
# Part 1: One number generated by computer, user has to guess until they get it
# Part 2: Add hints: higher / lower


# Part 2:
# Bonus: give hints: higher / lower
# Bonus: give hints: warmer / colder / the same
# Bonus: create different "levels" (ex. easier level # is 1-10, medium 1-50, hard 1-100 (solution below)

def number_guessing_game():
    # get difficulty from user
    difficulty = ""
    while difficulty not in ["e", "m", "h"]:
        difficulty = input("Choose a difficulty: (e)asy, (m)edium, or (h)ard")

    # get minimum and maximum number
    min = 1

    # max number is based on difficulty
    difficulty_to_max = {
        "e": 10,
        "m": 50,
        "h": 100
    }
    max = difficulty_to_max[difficulty]

    # generate a secret random number
    secret_number = random.randint(min, max)
    last_guess = 0
    guesses = 0  # keep track of the number of guesses

    # keep looping until they guess the secret number
    while last_guess != secret_number:
        last_guess = int(input(f"Guess the number! ({min}-{max}): "))
        # if the guess was out of the range
        if last_guess < min or last_guess > max:
            print(f"it should be in the range {min}-{max}")
            continue
        guesses += 1
        if last_guess < secret_number:
            print("higher")
        elif last_guess > secret_number:
            print("lower")

    print(f"You got it in {guesses} tries!")

number_guessing_game()